apiVersion: v1
kind: Service
metadata:
  name: author-service
spec:
  selector:
    app: author-deployment
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 30091
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-deployment
  labels:
    app: author-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: author-deployment
      labels:
        app: author-deployment
    spec:
      containers:
        - name: author-deployment
          image: ersanmaz/author-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
      #restartPolicy: Always
  selector:
    matchLabels:
      app: author-deployment
